[default]
APPLICATION_NAME="py-api"
APPLICATION_VERSION="1.0.0"
DEBUG=true
LOG_LEVEL="DEBUG"
GUNICORN_THREADS=1
GUNICORN_WORKERS=1
SQLALCHEMY_DATABASE_URI="mysql+pymysql://inventory:passwdInventory@27.72.88.106:3061/inventory"
SQLALCHEMY_TRACK_MODIFICATIONS=true
SWAGGER_URL="/apidocs"
SWAGGER_FILE="swagger.json"
REDIS_URL="redis://:6EbuHgXDJrAs5q9M@redis.tn20.wedesign.vn:9009/0"
REDIS_HOST="redis.tn20.wedesign.vn"
REDIS_PORT=9009
REDIS_PASSWORD="6EbuHgXDJrAs5q9M"

[docker]
SQLALCHEMY_DATABASE_URI="mysql+pymysql://api:api@db:3307/api"

[production]
SQLALCHEMY_DATABASE_URI="CONSIDER USING ENVIRONMENT VARIABLES FOR PRODUCTION"
GUNICORN_THREADS=10
GUNICORN_WORKERS=2